# Generated by Django 3.1.4 on 2020-12-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_img1', models.FileField(blank=True, null=True, upload_to='')),
                ('work_img2', models.FileField(blank=True, null=True, upload_to='')),
                ('my_img', models.FileField(blank=True, null=True, upload_to='')),
                ('icon', models.FileField(blank=True, null=True, upload_to='')),
                ('icon2', models.FileField(blank=True, null=True, upload_to='')),
                ('my_name', models.CharField(blank=True, max_length=256, null=True)),
                ('my_name_en', models.CharField(blank=True, max_length=256, null=True)),
                ('my_name_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('my_name_uz', models.CharField(blank=True, max_length=256, null=True)),
                ('my_info', models.TextField(blank=True, null=True)),
                ('my_info_en', models.TextField(blank=True, null=True)),
                ('my_info_ru', models.TextField(blank=True, null=True)),
                ('my_info_uz', models.TextField(blank=True, null=True)),
                ('icon_info', models.CharField(blank=True, max_length=256, null=True)),
                ('icon_info_en', models.CharField(blank=True, max_length=256, null=True)),
                ('icon_info_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('icon_info_uz', models.CharField(blank=True, max_length=256, null=True)),
                ('icon2_info', models.CharField(blank=True, max_length=256, null=True)),
                ('icon2_info_en', models.CharField(blank=True, max_length=256, null=True)),
                ('icon2_info_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('icon2_info_uz', models.CharField(blank=True, max_length=256, null=True)),
                ('f_name', models.CharField(blank=True, max_length=256, null=True)),
                ('f_name_en', models.CharField(blank=True, max_length=256, null=True)),
                ('f_name_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('f_name_uz', models.CharField(blank=True, max_length=256, null=True)),
                ('l_name', models.CharField(blank=True, max_length=256, null=True)),
                ('l_name_en', models.CharField(blank=True, max_length=256, null=True)),
                ('l_name_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('l_name_uz', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('message_en', models.TextField(blank=True, null=True)),
                ('message_ru', models.TextField(blank=True, null=True)),
                ('message_uz', models.TextField(blank=True, null=True)),
                ('btn', models.CharField(blank=True, max_length=256, null=True)),
                ('btn_en', models.CharField(blank=True, max_length=256, null=True)),
                ('btn_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('btn_uz', models.CharField(blank=True, max_length=256, null=True)),
                ('ins_icon', models.FileField(blank=True, null=True, upload_to='')),
                ('ins', models.CharField(blank=True, max_length=256, null=True)),
                ('tg_icon', models.FileField(blank=True, null=True, upload_to='')),
                ('tg', models.CharField(blank=True, max_length=256, null=True)),
                ('gmail_icon', models.FileField(blank=True, null=True, upload_to='')),
                ('gmail', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
