# Generated by Django 3.1.4 on 2020-12-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page Item', 'verbose_name_plural': 'Pages Items'},
        ),
    ]
