# Generated by Django 3.1.4 on 2020-12-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201213_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='email',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
